CREATE DATABASE merkleapi; 

\c merkleapi;    -> connect to database

\dt;   -> list tables

e

UQC1aLMDpuOmSaX5KvGACTyZZ4tcJOfCDgMcQR8rBdiFpwqj -> My Owner


0QB9hvA-zTQOmoX67l9VEbSFWHrRLkGp6Dpp1Tj3OchJwb9N

https://tonfishfull-0e0050d26a8c.herokuapp.com/nft/
https://tonfishfull-0e0050d26a8c.herokuapp.com/nft/collection.json



https://mekleapi-production.up.railway.app/admin/rediscover


./ctl genupd   1.json   UQC1aLMDpuOmSaX5KvGACTyZZ4tcJOfCDgMcQR8rBdiFpwqj   https://tonfishfull-0e0050d26a8c.herokuapp.com/nft/collection.json  https://tonfishfull-0e0050d26a8c.herokuapp.com/nft/   1 1 UQC1aLMDpuOmSaX5KvGACTyZZ4tcJOfCDgMcQR8rBdiFpwqj https://mekleapi-production.up.railway.app/v1







./ctl genupd   1.json   UQC1aLMDpuOmSaX5KvGACTyZZ4tcJOfCDgMcQR8rBdiFpwqj   https://raw.githubusercontent.com/MuhiaKevin/files/main/collection.json  https://github.com/MuhiaKevin/files/blob/main/   1 1 UQC1aLMDpuOmSaX5KvGACTyZZ4tcJOfCDgMcQR8rBdiFpwqj https://mekleapi-production.up.railway.app/v1











ctl genupd  apidata/upd/1.json 0QB9hvA-zTQOmoX67l9VEbSFWHrRLkGp6Dpp1Tj3OchJwb9N  https://raw.githubusercontent.com/MuhiaKevin/files/main/collection.json https://github.com/MuhiaKevin/files/blob/main/ 1 1  0QB9hvA-zTQOmoX67l9VEbSFWHrRLkGp6Dpp1Tj3OchJwb9N  http://localhost:8081/v1












https://app.tonkeeper.com/transfer/EQDM9Srp6c6RqnzMnJyDUmJv5r-j8xPR3cZnSd78gORzr-q_?amount=50000000&init=te6cckECOwEABagAAgE0ARsBFP8A9KQT9LzyyAsCAgFiAyoCAswGBAIBIBQFAFXTeAODfGOEt8IVKpCFzNrjfAkHgCCTfGANJ0GHwheAX8IIldeXAy_DD4AcAgEgDgcCASALCAIBIAoJAC0AcjLP_gozxbJcCDIywET9AD0AMsAyYAALND6QNQwgAgEgDQwAXRwBNCTU0G5jh5TJK1xsJgg1wv_UATwBJcg1wv_FPAE4gPXTNAEpAToEDRfBAG6gABMAcjL_8v_yfkAgAgEgEQ8CASATEAA5PhH-Eb4RfhD-EL4QcjL_8sHzPhEzxbMzMzJ7VSABy0MyLHAJJfA-DQ0wMBcbCSXwPg-kAw8AIC0x_TPyKCCTo8prqOGTRbghAFEP9AvvLgZtQB0AHT_zAB1NQw8ArgMyGCCjzVLLqdW_hEEscF8uBk1DDwDOAyghBpPTlQuuMCW4QP8vCBIATPhG0IIQqMsArXCAEMjLBVAFzxYk-gIUy2oTyx_LPwHPFsmAQPsAAEc7UTQ0_8B-GHTBwH4YtQB-GP6QAH4ZNQB-GXUAfhm1AH4Z9GACASAVGAIBIBcWAD0-EMT8Acg8Ah3gBjIywVYzxZQA_oCEstrzMzJcfsAgABs-QBwdMjLAsoHy__J0IAIBIBoZAFsAtDSAAGf0gDT_zABk2whIOACb4EB4NQjpVQiMPALAtQwBKVEMPALWfAEWfAEgAEE-EEi-QD4QiUQNAHwBfLgZfAGggnJw4DIUAPPFszJ8AmAEhT8RPof-7XfE7dPi7wgDiuZ0qv3SRPvOOJOJVY0zCssEFIAPsN4H2aaB01C_XcvqojaQqw9aJcg1PQdNOqce5zkJODAfOB4cAQIBHQBaaHR0cHM6Ly9tZWtsZWFwaS1wcm9kdWN0aW9uLnVwLnJhaWx3YXkuYXBwL3YxAEsAAQABgA-w3gfZpoHTUL9dy-qiNpCrD1olyDU9B006px7nOQk4MAEU_wD0pBP0vPLICyACAWIiIQAJoR-f4AUCAs4jNQIBICUkABE-kQwwADy4U2ACzwyIccAkl8D4NDTAwFxsJJfA-D6QPpAMfoAMXHXIfoAMfoAMHOptADwAgSzjhQwbCI0UjLHBfLhlQH6QNQwECPwA-AG0x_TP4IQX8w9FFIwuuMCMDQ0NTWCEC_LJqISuuMCXwSED_LwgJyYAcnCCEIt3FzUFyMv_UATPFhAkgEBwgBDIywVQB88WUAX6AhXLahLLH8s_Im6zlFjPFwGRMuIByQH7AAKsMhA3XjJAE1E1xwXy4ZH6QCHwAfpA0gAx-gAg10nCAPLixIIK-vCAG6EhlFMVoKHeItcLAcMAIJIGoZE24iDC__LhkiGUECo3W-MNApMwMjTjDVUC8AMpKABqJvABghDVMnbbEDdEAG1xcIAQyMsFUAfPFlAF-gIVy2oSyx_LPyJus5RYzxcBkTLiAckB-wAAfIIQBRONkchQCc8WUAvPFnEkSRRURqBwgBDIywVQB88WUAX6AhXLahLLH8s_Im6zlFjPFwGRMuIByQH7ABBHAgEgLisCAUgtLAANtQ2eAF8IMAAbtgt-AF8Iug_gOoYfCJACASA0LwIBIDEwABW09H4AXwh-AP4BEAIBSDMyAB2va_gBfCNoaYfph_0gGEAAF66f-AF8I-hpg-oYQAAtuLXTHwAvhF0NQx1DDQccjLBwHPFszJgCASA2NwA7O1E0NM_-kAg10nCAJp_AfpA1DAQJBAj4DBwWW1tgAB0A8jLP1jPFgHPFszJ7VSACADo5AGZodHRwczovL3RvbmZpc2hmdWxsLTBlMDA1MGQyNmE4Yy5oZXJva3VhcHAuY29tL25mdC8AhgFodHRwczovL3RvbmZpc2hmdWxsLTBlMDA1MGQyNmE4Yy5oZXJva3VhcHAuY29tL25mdC9jb2xsZWN0aW9uLmpzb27Liy5Q
